global:
  resolve_timeout: 5m

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://webhook-receiver:5001/'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'webhook'


